Debug reengineered pipeline

diff --git a/packages/bash_functions b/packages/bash_functions
--- a/packages/bash_functions
+++ b/packages/bash_functions
@@ -6,3 +6,68 @@ _exit_if_failed () {
         exit ${_rc};
     fi
 }
+
+_build_cmake () {
+    src_dir=$1
+    _eif=${2-0}
+    ret_code=0
+    if [ ! -e ${src_dir} ]; then
+        echo "FAILED: directory not found: ${src_dir}";
+        ret_code=127;
+    else
+        cd ${src_dir} && \
+        mkdir -p ${src_dir}/build \
+        && cd ${src_dir}/build \
+        && ${CLEAN_BUILD} \
+        && ${CM} \
+        && ${MAKE_CMD} \
+        || ret_code=1;
+
+        if [ $ret_code == 0 ]; then
+            echo "OK: built $src_dir";
+        else
+            echo "FAILED building: $src_dir";
+        fi
+    fi
+    if [ $_eif != 0 ]; then
+        _exit_if_failed $ret_code "compilation of ${src_dir}"
+    fi
+    return $ret_code
+}
+
+_run_cli_unit_test () {
+    build_dir=$1
+    exe_name=$2
+    _eif=${3-0} # exit if failed
+    _rc=0
+    if [ ! -e ${build_dir} ]; then
+        echo "FAILED: directory not found: ${build_dir}";
+        _rc=127;
+    else
+        cd ${build_dir};
+        if [ ! -e ${exe_name} ]; then
+            echo "FAILED: file ${exe_name} not found in ${build_dir}";
+            _rc=127;
+        else
+            ./${exe_name}
+            ret_code=$?
+            if [ $ret_code != 0 ]; then 
+                echo FAILED: unit test ${exe_name} return code is not 0 but $ret_code
+                _rc=$ret_code;
+            fi
+        fi
+    fi
+    if [ $_eif != 0 ]; then
+        _exit_if_failed $_rc "unit tests ${exe_name}"
+    fi
+    return $_rc
+}
+
+_print_banner() {
+    echo
+    echo "==============================================="
+    echo $1
+    echo "==============================================="
+    echo
+}
+
